name: Build and deploy Python project to Azure Function App - dev-func-app-Kupune

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Ensure azure-functions is in requirements
        run: |
          grep -q "azure-functions" requirements.txt || echo "azure-functions" >> requirements.txt
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir package
          cp host.json requirements.txt package/
          cp -r HttpTrigger1 package/
          cd package
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5761C2DB0AA14A089A307B1632507D56 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2BE29AA2E37B472285210CCDC6FED1BC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_07C1933435CD4CE2B59BCD1400F4DFC2 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'dev-func-app-Kupune'
          slot-name: 'Production'
          package: release.zip
